language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "3.4"
  - "2.7"

branches:
  only:
    - master

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-test.txt

install:
  - python setup.py -q develop

before_script:
  - openwisp-utils-qa-checks --skip-checkmigrations
  - mkdir docs/source/_static
  - sphinx-build -W -b html docs/source docs/_build

script:
  - nose2 --with-coverage --coverage=netjsonconfig

after_success:
  coveralls
